language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - webapp/node_modules

before_script:
  - cd webapp

script:
  - yarn
  - git diff
  - yarn lint
  - yarn build
  - yarn test
  - yarn percy

